---
name: Deploy

on:
  push:
    branches: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Call npm deploy
        run: npm install && npm run deploy
    
    
    
